### ISSUE TITLE
Find out why including the "clean" goal breaks the build

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/projectwizard-portlet#3]
I am not sure what's the issue, but here's what I know:

  - Travis executes `mvn clean cobertura:cobertura install` and it loudly complains: 
   ```
   [ERROR] Unexpected internal compiler error
   [INFO] java.lang.IncompatibleClassChangeError: 
      class com.google.gwt.dev.javac.asm.CollectMethodData has interface org.objectweb.asm.MethodVisitor as super class
   ```
Each of the following tests were executed starting from a clean local git repository (i.e., `rm -Rf projectwizard-portlet/ && git clone http://github.com/qbicsoftware/projectwizard-portlet && cd projectwizard-portlet && mvn ...`), using the default development branch:
  - `mvn clean cobertura:cobertura install` generates the same error.
  - `mvn clean cobertura:cobertura package` fails in the same way.
  - However, running any of the following *does not* produce an error:
    - `mvn clean cobertura:cobertura`
    - `mvn clean && mvn cobertura:cobertura install`
    - `mvn cobertura:cobertura install`
    - `mvn clean test install`

So I believe this seems to be a problem with how the cobertura plugin has been configured and that strange library giving problems, but this is just a hunch.

**Comment by chahuistle** [comment]
Worst case scenario, we can remove the `clean` goal from the Travis builds: it might be redundant, but still, this is not a proper fix of the problem, just a workaround (but then, we would have to update all copies of `.travis.yml`, because it's not still automatic).

**Comment by chahuistle** [comment]
Workaround seems to do the trick!
https://github.com/qbicsoftware/projectwizard-portlet/commit/1a5cee78354750a45d2b9ffea03bb255ed4a5c61

**Comment by wow-such-code** [comment]
not relevant anymore
